### ISSUE TITLE
definition file error

### ISSUE THREAD

**Issue by Elwag** [WOA-Project/DriverUpdater#12]
While trying to install [these drivers](https://github.com/Icesito68/7xx-Drivers) to my Poco X3 NFC (surya), I get this error:

```
[11:54:04][   Error   ] Something happened!
[11:54:04][   Error   ] System.InvalidOperationException: There is an error in XML document (1, 1).
 ---> System.Xml.XmlException: Data at the root level is invalid. Line 1, position 1.
   at System.Xml.XmlTextReaderImpl.Throw(Exception e)
   at System.Xml.XmlTextReaderImpl.Throw(String res, String arg)
   at System.Xml.XmlTextReaderImpl.ParseRootLevelWhitespace()
   at System.Xml.XmlTextReaderImpl.ParseDocumentContent()
   at System.Xml.XmlReader.MoveToContent()
   at Microsoft.Xml.Serialization.GeneratedAssembly.XmlSerializationReaderFeatureManifest.Read12_FeatureManifest()
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodBaseInvoker.InvokeWithNoArgs(Object obj, BindingFlags invokeAttr)
   --- End of inner exception stack trace ---
   at System.Xml.Serialization.XmlSerializer.Deserialize(XmlReader xmlReader, String encodingStyle, XmlDeserializationEvents events)
   at System.Xml.Serialization.XmlSerializer.Deserialize(Stream stream)
   at DriverUpdater.DefinitionParser..ctor(String DefinitionFile)
   at DriverUpdater.Program.InstallDrivers(String Definition, String DriverRepo, String DrivePath)
   at DriverUpdater.Program.DriverUpdaterAction(String Definition, String DriverRepo, String DevicePart)
```
   
I didn't get the drivers from the releases, I cloned the whole repository.

I ran the command through a admin-cmd, in a normal cmd, UAC would ask for admin privileges and around 1 second after granting those, the program just closed without (that's what I think) doing anything.

This is the command I ran:
`DriverUpdater.exe -d 7xx-Drivers-main\definitions\Desktop\ARM64\Internal\surya.txt -r 7xx-Drivers-main -p X:`
This is out of [this](https://github.com/SebastianZSXS/Poco-X3-NFC-WindowsARM/blob/main/language/english.md) instruction.

Allthough I think it has something to do with the definitions file of the repository, maybe someone here can still help me.
Thanks!

**Comment by Elwag** [comment]
It seems that the new driverupdaters are only prepared for use with xml, these drivers still use txt.
