### ISSUE TITLE
Driver Updater, "Something happened?"

### ISSUE THREAD

**Issue by OrionGrant** [WOA-Project/DriverUpdater#3]
I'm getting the following message when trying to update my drivers, please help!

`C:\>UpdatedDrivers\DriverUpdater.exe C:\UpdatedDrivers\Lumia-Drivers-XXXX\definitions\Desktop\Internal\950.txt C:\UpdatedDrivers\Lumia-Drivers-XXXX\ G:\
[11:51:49][Information] DriverUpdater 1.0.0.0 - Cleans and Installs a new set of drivers onto a Windows Image
[11:51:49][Information] Copyright (c) 2017-2021, The LumiaWOA Authors
[11:51:49][Information] https://github.com/WOA-Project/DriverUpdater

[11:51:49][Information] This program comes with ABSOLUTELY NO WARRANTY.
[11:51:49][Information] This is free software, and you are welcome to redistribute it under certain conditions.

[11:51:49][Information] Reading definition file...
[11:51:49][   Error   ] Something happened!
[11:51:49][   Error   ] System.NotImplementedException: Support for replaying registry log file
   at DiscUtils.Registry.HiveHeader.ReadFrom(Byte[] buffer, Int32 offset)
   at DiscUtils.Registry.RegistryHive..ctor(Stream hive, Ownership ownership)
   at DriverUpdater.Program.ResealForPnPFirstBootUx(String DevicePart)
   at DriverUpdater.Program.Install(String Definition, String DriverRepo, String DevicePart, Boolean IntegratePostUpgrade, Boolean IsARM)
   at DriverUpdater.Program.Main(String[] args)
[11:51:49][Information] Done!`

**Comment by gus33000** [comment]
Phone was incorrectly shutdown, a fix for this is coming very soon (it's already in master in fact just yet to be released)
